### ISSUE TITLE
List of builder todo notes

### ISSUE THREAD

**Issue by Cablefish1** [zunath/Freescape_JVM#135]
- [x] Mauwi Wetlands East: Skullcap plant (old plant, need to go)

- [x] Mothbite Marshes - East Ruins: Ruined Library description trigger (swear i've already done this)
- [x] Morano Lake - South Edge: Broken area transition
- [x] Morano Hills - Central: Minable Rock - Tin (old resource. Needs to go)
- [x] Morano Hills - Central: Loose Rocks (old resource. Needs to go)
- [x] Morano Hills - East River : Random Surface Bird (old placeable. Needs to go)
- [x] Morano Hills - East River : Area transition only going one way.
